import { Minus, Plus, Trash2, X, ShoppingBag, MessageCircle } from 'lucide-react'
import { currentPrice, money } from '../utils/format'
import { openWhatsAppOrder } from '../utils/whatsapp'
import { siteConfig } from '../config/siteConfig'
import { useStore } from '../context/StoreContext'

export function CartDrawer({ open, onClose }) {
  const { cart, setQuantity, removeFromCart, settings } = useStore()
  const subtotal = cart.reduce((n, item) => n + currentPrice(item.product) * item.quantity, 0)
  const delivery = subtotal >= siteConfig.delivery.freeOver || subtotal === 0 ? 0 : siteConfig.delivery.outside
  const total = subtotal + delivery
  const whatsapp = () => { try { openWhatsAppOrder({ items: cart, total, deliveryCharge: delivery, whatsappNumber: settings.whatsappNumber }) } catch (e) { alert(e.message) } }
  return <><button className={`drawer-scrim ${open ? 'visible' : ''}`} onClick={onClose} aria-label="Close cart" tabIndex={open ? 0 : -1}/><aside className={`cart-drawer ${open ? 'open' : ''}`} aria-label="Shopping cart" aria-modal="true" role="dialog" aria-hidden={!open}><div className="drawer-head"><div><span className="eyebrow">YOUR LITTLE FINDS</span><h2>Your bag <span>({cart.reduce((n, i) => n + i.quantity, 0)})</span></h2></div><button className="icon-btn" onClick={onClose} aria-label="Close cart"><X/></button></div>{cart.length === 0 ? <div className="empty-cart"><div className="empty-bag"><ShoppingBag size={30}/></div><h3>A little room for something lovely.</h3><p>Your bag is waiting for its first find.</p><button className="button button-dark" onClick={onClose}>Explore the shop</button></div> : <><div className="cart-items">{cart.map(item => <div className="cart-line" key={item.key}><img src={item.product.images[0]} alt=""/><div className="cart-line-detail"><h3>{item.product.name}</h3><small>{[item.size, item.color].filter(Boolean).join(' · ')}</small><strong>{money(currentPrice(item.product))}</strong><div className="quantity-control"><button onClick={() => setQuantity(item.key, item.quantity - 1)} aria-label="Decrease quantity"><Minus size={13}/></button><span>{item.quantity}</span><button onClick={() => setQuantity(item.key, Math.min(item.product.stock, item.quantity + 1))} aria-label="Increase quantity" disabled={item.quantity >= item.product.stock}><Plus size={13}/></button></div></div><button className="remove-line" onClick={() => removeFromCart(item.key)} aria-label="Remove item"><Trash2 size={16}/></button></div>)}</div><div className="drawer-bottom"><p className="delivery-note">{delivery === 0 ? 'You have unlocked free delivery ✳' : `Delivery estimate ${money(delivery)} · Free over ${money(siteConfig.delivery.freeOver)}`}</p><div className="total-row"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div className="total-row"><span>Delivery estimate</span><span>{delivery ? money(delivery) : 'Free'}</span></div><div className="total-row grand-total"><span>Total</span><strong>{money(total)}</strong></div><button className="button button-outline" onClick={whatsapp}><MessageCircle size={17}/> Send bag on WhatsApp</button><button className="continue-link" onClick={onClose}>Continue shopping</button></div></>}</aside></>
}
